insert into album (id, name, release_date) values (1, 'Bupivacaine Hydrochloride', '2008-04-17');
insert into album (id, name, release_date) values (2, 'Baptisia tinctoria, Echinacea, Phytolacca decandra', '1962-12-22');
insert into album (id, name, release_date) values (3, 'Naproxen', '1960-08-09');
insert into album (id, name, release_date) values (4, 'Enalapril Maleate and Hydrochlorothiazide', '1958-03-05');
insert into album (id, name, release_date) values (5, 'PREDNISOLONE SODIUM PHOSPHATE', '2010-06-05');
insert into album (id, name, release_date) values (6, 'Levothyroxine Sodium', '1988-03-30');
insert into album (id, name, release_date) values (7, 'penciclovir', '2009-12-12');
insert into album (id, name, release_date) values (8, 'Zidovudine', '1976-02-24');
insert into album (id, name, release_date) values (9, 'Pyridostigmine Bromide', '1974-09-18');
insert into album (id, name, release_date) values (10, 'OCTINOXATE', '2015-07-06');
insert into album (id, name, release_date) values (11, 'Chlorpheniramine Maleate', '2008-08-20');
insert into album (id, name, release_date) values (12, 'Amlodipine Besylate', '1997-07-18');
insert into album (id, name, release_date) values (13, 'HEPARIN SODIUM', '1998-08-28');
insert into album (id, name, release_date) values (14, 'Bayberry', '2008-09-11');
insert into album (id, name, release_date) values (15, 'Stannous Fluoride', '1951-10-20');
insert into album (id, name, release_date) values (16, 'CUPRUM METALLICUM', '1978-06-20');
insert into album (id, name, release_date) values (17, 'Sodium Phenylbutyrate', '1988-11-30');
insert into album (id, name, release_date) values (18, 'Sumatriptan Succinate', '1994-12-04');
insert into album (id, name, release_date) values (19, 'Wild oat,', '1970-05-13');
insert into album (id, name, release_date) values (20, 'Ketorolac Tromethamine', '1982-07-28');
insert into album (id, name, release_date) values (21, 'Aluminum Hydroxide, Magnesium Hydroxide, Simethicone', '1985-12-30');
insert into album (id, name, release_date) values (22, 'WITCH HAZEL', '2008-08-06');
insert into album (id, name, release_date) values (23, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', '1999-10-02');
insert into album (id, name, release_date) values (24, 'Naltrexone Hydrochloride', '2011-02-09');
insert into album (id, name, release_date) values (25, 'Pseudoephedrine Hydrochloride', '1996-12-24');
insert into album (id, name, release_date) values (26, 'fentanyl', '2002-05-13');
insert into album (id, name, release_date) values (27, 'naproxen', '1999-04-05');
insert into album (id, name, release_date) values (28, 'potassium citrate', '2010-05-20');
insert into album (id, name, release_date) values (29, 'DOXORUBICIN HYDROCHLORIDE', '1965-12-14');
insert into album (id, name, release_date) values (30, 'Stavudine', '2004-05-03');
insert into album (id, name, release_date) values (31, 'FENOLDOPAM MESYLATE', '1975-05-29');
insert into album (id, name, release_date) values (32, 'Levothyroxine Sodium', '1982-02-02');
insert into album (id, name, release_date) values (33, 'CETYLPYRIDINIUM CHLORIDE', '1985-05-28');
insert into album (id, name, release_date) values (34, 'Atenolol', '2015-05-01');
insert into album (id, name, release_date) values (35, 'Miconazole Nitrate', '1967-01-28');
insert into album (id, name, release_date) values (36, 'erythromycin', '1997-02-24');
insert into album (id, name, release_date) values (37, 'dimethicone, octinoxate, octisalate, oxybenzone', '1986-11-10');
insert into album (id, name, release_date) values (38, 'BENZOYL PEROXIDE', '1963-01-05');
insert into album (id, name, release_date) values (39, 'Amoxicillin', '1992-12-02');
insert into album (id, name, release_date) values (40, 'Lidocaine Hydrochloride and Epinephrine Bitartrate', '2012-06-28');
insert into album (id, name, release_date) values (41, 'risperidone', '2000-07-01');
insert into album (id, name, release_date) values (42, 'Quinapril', '1978-08-12');
insert into album (id, name, release_date) values (43, 'ETHYL ALCOHOL', '2011-02-14');
insert into album (id, name, release_date) values (44, 'Arsenicum alb., Baptisia, Berber. aqui., Calc. fluor., Capsicum, Cinchona, Iodium, Kali carb., Lachesis, Mag. carb., Merc.viv., Nat. carb., Nat. mur., Natrum sulphuricum, Phosphorus, Phytolacca, Secale, Thymus serpyllum, Thuja occ., Thyroidinum, Verbascum, Carduus mar., Echinacea, Solidago, Taraxacum', '1976-04-13');
insert into album (id, name, release_date) values (45, 'Utah Juniper', '1992-09-14');
insert into album (id, name, release_date) values (46, 'Niacin, Melatonin, Nadidum, Pyridoxinum hydrochloricum, Zincum sulphuricum, Hypothalamus, Lithium carbonicum, Magnesia carbonica, Pineal, Pituitary,', '1997-10-17');
insert into album (id, name, release_date) values (47, 'dl-camphor, l-menthol, methyl salicylate', '1962-06-03');
insert into album (id, name, release_date) values (48, 'OCTINOXATE and TITANIUM DIOXIDE', '1977-11-09');
insert into album (id, name, release_date) values (49, 'Venlafaxine', '1998-09-13');
insert into album (id, name, release_date) values (50, 'Hydrocortisone', '1982-10-09');
insert into album (id, name, release_date) values (51, 'Lithium Carbonate', '1971-07-14');
insert into album (id, name, release_date) values (52, 'glipizide', '1970-01-13');
insert into album (id, name, release_date) values (53, 'Petroleum', '1960-01-23');
insert into album (id, name, release_date) values (54, 'warfarin sodium', '2016-01-07');
insert into album (id, name, release_date) values (55, 'Metoclopramide Hydrochloride', '1982-04-29');
insert into album (id, name, release_date) values (56, 'Arsenicum iodatum, Blatta orientalis, Bryonia, Carbo vegetabilis, Eupatorium perfoliatum, Histaminum hydrochloricum, Ipecacuanha, Lung suis,', '1982-11-02');
insert into album (id, name, release_date) values (57, 'Povidone-Iodine, Lidocaine Hydrochloride, Benzalkonium Chloride', '1995-08-31');
insert into album (id, name, release_date) values (58, 'Mirtazapine', '1953-04-15');
insert into album (id, name, release_date) values (59, 'Alfalfa, Avena sativa, Baryta carbonica, Baryta Iodata, Baryta muriatica, Calcarea carbonica, Calcarea fluorica, Calcarea phosphorica, Lycopodium clavatum, Thuja occidentalis', '1971-11-19');
insert into album (id, name, release_date) values (60, 'PULSATILLA VULGARIS', '1990-12-02');
insert into album (id, name, release_date) values (61, 'Dicyclomine Hydrochloride', '1970-11-26');
insert into album (id, name, release_date) values (62, 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine', '2002-02-11');
insert into album (id, name, release_date) values (63, 'Curvularia lunata', '2014-06-22');
insert into album (id, name, release_date) values (64, 'Naproxen', '1966-09-29');
insert into album (id, name, release_date) values (65, 'Propafenone hydrochloride', '1970-04-19');
insert into album (id, name, release_date) values (66, 'Witch Hazel', '1955-03-01');
insert into album (id, name, release_date) values (67, 'Calcarea carbonica 12X, Fucus vesiculosus 4X, Graphites 12X, Natrum sulphuricum 4X, Spongia tosta 4X', '2001-06-21');
insert into album (id, name, release_date) values (68, 'donepezil hydrochloride', '1996-11-04');
insert into album (id, name, release_date) values (69, 'Titanium Dioxide, Zinc Oxide', '1967-11-20');
insert into album (id, name, release_date) values (70, 'memantine hydrochloride', '1984-04-06');
insert into album (id, name, release_date) values (71, 'Apis Mellifica, Cantharis, Graphites, Natrum Muriaticum, Rhus Glabra, Rhus Toxicodendron, Rhus Venenata, Urtica Dioica', '1972-10-31');
insert into album (id, name, release_date) values (72, 'ALCOHOL', '1955-09-20');
insert into album (id, name, release_date) values (73, 'NITROGEN', '1965-07-15');
insert into album (id, name, release_date) values (74, 'Oxygen', '1997-05-23');
insert into album (id, name, release_date) values (75, 'Metoprolol Succinate', '2007-06-07');
insert into album (id, name, release_date) values (76, 'Oxygen', '2006-09-04');
insert into album (id, name, release_date) values (77, 'Johnson Grass Sorghum halepense', '2016-12-14');
insert into album (id, name, release_date) values (78, 'OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE', '1960-06-01');
insert into album (id, name, release_date) values (79, 'Methylprednisolone', '1950-07-26');
insert into album (id, name, release_date) values (80, 'diltiazem hydrochloride', '1998-05-13');
insert into album (id, name, release_date) values (81, 'Tolnaftate', '2000-12-08');
insert into album (id, name, release_date) values (82, 'Ibuprofen', '2006-03-31');
insert into album (id, name, release_date) values (83, 'Foaming Instant Hand Sanitizer with Aloe and Vitamin E', '1993-08-22');
insert into album (id, name, release_date) values (84, 'Oxygen', '2002-01-10');
insert into album (id, name, release_date) values (85, 'Acetaminophen, Dextromethorphan HBr, Doxylamine Succinate, Phenylephrine HCl', '1972-10-14');
insert into album (id, name, release_date) values (86, 'Triaminic Cough and Sore Throat', '1973-06-01');
insert into album (id, name, release_date) values (87, 'Sulindac', '1986-10-21');
insert into album (id, name, release_date) values (88, 'TITANIUM DIOXIDE', '1999-05-28');
insert into album (id, name, release_date) values (89, 'Triclosan', '1968-01-22');
insert into album (id, name, release_date) values (90, 'Gabapentin', '1991-09-11');
insert into album (id, name, release_date) values (91, 'Chlorpheniramine Maleate', '2011-12-10');
insert into album (id, name, release_date) values (92, 'Salicylic Acid', '1983-07-05');
insert into album (id, name, release_date) values (93, 'Naproxen Sodium', '1985-10-31');
insert into album (id, name, release_date) values (94, 'Lidocaine Hydrochloride and Epinephrine Bitartrate', '1965-04-26');
insert into album (id, name, release_date) values (95, 'Ibuprofen', '1998-06-20');
insert into album (id, name, release_date) values (96, 'diphenhydramine citrate and ibuprofen', '2001-06-25');
insert into album (id, name, release_date) values (97, 'Metoprolol succinate', '1977-12-05');
insert into album (id, name, release_date) values (98, 'Oxymetazoline HCl', '1976-06-18');
insert into album (id, name, release_date) values (99, 'OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE', '1988-05-10');
insert into album (id, name, release_date) values (100, 'Isopropyl Alcohol', '2006-08-01');
