INSERT INTO country VALUES (1, 'Afghanistan');
INSERT INTO country VALUES (2, 'Albania');
INSERT INTO country VALUES (3, 'Algeria');
INSERT INTO country VALUES (4, 'American Samoa');
INSERT INTO country VALUES (5, 'Andorra');
INSERT INTO country VALUES (6, 'Angola');
INSERT INTO country VALUES (7, 'Anguilla');
INSERT INTO country VALUES (8, 'Antarctica');
INSERT INTO country VALUES (9, 'Antigua and Barbuda');
INSERT INTO country VALUES (10, 'Argentina');
INSERT INTO country VALUES (11, 'Armenia');
INSERT INTO country VALUES (12, 'Aruba');
INSERT INTO country VALUES (13, 'Australia');
INSERT INTO country VALUES (14, 'Austria');
INSERT INTO country VALUES (15, 'Azerbaijan');
INSERT INTO country VALUES (16, 'Bahamas');
INSERT INTO country VALUES (17, 'Bahrain');
INSERT INTO country VALUES (18, 'Bangladesh');
INSERT INTO country VALUES (19, 'Barbados');
INSERT INTO country VALUES (20, 'Belarus');
INSERT INTO country VALUES (21, 'Belgium');
INSERT INTO country VALUES (22, 'Belize');
INSERT INTO country VALUES (23, 'Benin');
INSERT INTO country VALUES (24, 'Bermuda');
INSERT INTO country VALUES (25, 'Bhutan');
INSERT INTO country VALUES (26, 'Bolivia');
INSERT INTO country VALUES (27, 'Bosnia and Herzegovina');
INSERT INTO country VALUES (28, 'Botswana');
INSERT INTO country VALUES (29, 'Bouvet Island');
INSERT INTO country VALUES (30, 'Brazil');
INSERT INTO country VALUES (31, 'British Indian Ocean Territory');
INSERT INTO country VALUES (32, 'Brunei Darussalam');
INSERT INTO country VALUES (33, 'Bulgaria');
INSERT INTO country VALUES (34, 'Burkina Faso');
INSERT INTO country VALUES (35, 'Burundi');
INSERT INTO country VALUES (36, 'Cambodia');
INSERT INTO country VALUES (37, 'Cameroon');
INSERT INTO country VALUES (38, 'Canada');
INSERT INTO country VALUES (39, 'Cape Verde');
INSERT INTO country VALUES (40, 'Cayman Islands');
INSERT INTO country VALUES (41, 'Central African Republic');
INSERT INTO country VALUES (42, 'Chad');
INSERT INTO country VALUES (43, 'Chile');
INSERT INTO country VALUES (44, 'China');
INSERT INTO country VALUES (45, 'Christmas Island');
INSERT INTO country VALUES (46, 'Cocos (Keeling) Islands');
INSERT INTO country VALUES (47, 'Colombia');
INSERT INTO country VALUES (48, 'Comoros');
INSERT INTO country VALUES (49, 'Congo');
INSERT INTO country VALUES (50, 'Cook Islands');
INSERT INTO country VALUES (51, 'Costa Rica');
INSERT INTO country VALUES (52, 'Croatia (Hrvatska)');
INSERT INTO country VALUES (53, 'Cuba');
INSERT INTO country VALUES (54, 'Cyprus');
INSERT INTO country VALUES (55, 'Czech Republic');
INSERT INTO country VALUES (56, 'Denmark');
INSERT INTO country VALUES (57, 'Djibouti');
INSERT INTO country VALUES (58, 'Dominica');
INSERT INTO country VALUES (59, 'Dominican Republic');
INSERT INTO country VALUES (60, 'East Timor');
INSERT INTO country VALUES (61, 'Ecuador');
INSERT INTO country VALUES (62, 'Egypt');
INSERT INTO country VALUES (63, 'El Salvador');
INSERT INTO country VALUES (64, 'Equatorial Guinea');
INSERT INTO country VALUES (65, 'Eritrea');
INSERT INTO country VALUES (66, 'Estonia');
INSERT INTO country VALUES (67, 'Ethiopia');
INSERT INTO country VALUES (68, 'Falkland Islands (Malvinas)');
INSERT INTO country VALUES (69, 'Faroe Islands');
INSERT INTO country VALUES (70, 'Fiji');
INSERT INTO country VALUES (71, 'Finland');
INSERT INTO country VALUES (72, 'France');
INSERT INTO country VALUES (73, 'France, Metropolitan');
INSERT INTO country VALUES (74, 'French Guiana');
INSERT INTO country VALUES (75, 'French Polynesia');
INSERT INTO country VALUES (76, 'French Southern Territories');
INSERT INTO country VALUES (77, 'Gabon');
INSERT INTO country VALUES (78, 'Gambia');
INSERT INTO country VALUES (79, 'Georgia');
INSERT INTO country VALUES (80, 'Germany');
INSERT INTO country VALUES (81, 'Ghana');
INSERT INTO country VALUES (82, 'Gibraltar');
INSERT INTO country VALUES (83, 'Guernsey');
INSERT INTO country VALUES (84, 'Greece');
INSERT INTO country VALUES (85, 'Greenland');
INSERT INTO country VALUES (86, 'Grenada');
INSERT INTO country VALUES (87, 'Guadeloupe');
INSERT INTO country VALUES (88, 'Guam');
INSERT INTO country VALUES (89, 'Guatemala');
INSERT INTO country VALUES (90, 'Guinea');
INSERT INTO country VALUES (91, 'Guinea-Bissau');
INSERT INTO country VALUES (92, 'Guyana');
INSERT INTO country VALUES (93, 'Haiti');
INSERT INTO country VALUES (94, 'Heard and Mc Donald Islands');
INSERT INTO country VALUES (95, 'Honduras');
INSERT INTO country VALUES (96, 'Hong Kong');
INSERT INTO country VALUES (97, 'Hungary');
INSERT INTO country VALUES (98, 'Iceland');
INSERT INTO country VALUES (99, 'India');
INSERT INTO country VALUES (100, 'Isle of Man');
